#!/bin/sh

INSTALL_DIR="$HOME/.deploymeteor"

if [ ! -d "$INSTALL_DIR" ];
then
	git clone http://github.com/aldeed/deploymeteor.git "$INSTALL_DIR"
else
	cd "$INSTALL_DIR"
	git pull
fi

if [ ! -f /usr/local/bin/deploymeteor ];
then
	sudo ln -s "$INSTALL_DIR/deploymeteor.sh" /usr/local/bin/deploymeteor
fi